id: PA18744B8
initial_creation_type: ocr
source_metadata:
  volumes:
    b9da97d260854540889389f3429199a3:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: བཅོམ་ལྡན་འདས་ལ་བསྟོད་པ་དཔལ་རྡོ་རྗེ་འཛིན་གྱི་དབྱངས་ཀྱི་རྒྱ་ཆེར་བཤད་པ།
      total_pages: 1539
      volume_number: 1
